# Generated by Django 4.2.13 on 2026-03-20 00:23

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.users.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("ADMIN", "Coordinador"), ("EVALUATOR", "Educador")],
                default="EVALUATOR",
                max_length=20,
            ),
        ),
    ]
