# Generated by Django 4.2.13 on 2026-03-10 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stationassignment",
            name="evaluator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Evaluador",
            ),
        ),
        migrations.AddField(
            model_name="stationassignment",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="exams.exam",
                verbose_name="ECOE",
            ),
        ),
        migrations.AddField(
            model_name="stationassignment",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="exams.station",
                verbose_name="Estación",
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stations",
                to="exams.exam",
                verbose_name="ECOE",
            ),
        ),
        migrations.AddField(
            model_name="rubricitem",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rubric_items",
                to="exams.station",
                verbose_name="Estación",
            ),
        ),
        migrations.AddField(
            model_name="gradescalepoint",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grade_scale",
                to="exams.station",
                verbose_name="Estación",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_exams",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stationassignment",
            unique_together={("exam", "station", "evaluator")},
        ),
        migrations.AlterUniqueTogether(
            name="gradescalepoint",
            unique_together={("station", "raw_points")},
        ),
    ]
