# Generated by Django 4.2.13 on 2026-03-20 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0003_exam_type_variants_passing_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stationassignment",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="exams.exam",
                verbose_name="Evaluación",
            ),
        ),
    ]
