# Generated by Django 4.2.13 on 2026-03-10 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("rut", models.CharField(max_length=20, unique=True, verbose_name="RUT")),
                ("full_name", models.CharField(max_length=200, verbose_name="Nombre completo")),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Correo electrónico"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Estudiante",
                "verbose_name_plural": "Estudiantes",
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="ExamStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_students",
                        to="exams.exam",
                        verbose_name="ECOE",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_students",
                        to="students.student",
                        verbose_name="Estudiante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estudiante en ECOE",
                "verbose_name_plural": "Estudiantes en ECOE",
                "ordering": ["student__full_name"],
                "unique_together": {("exam", "student")},
            },
        ),
    ]
