# Generated by Django 4.2.13 on 2026-03-10 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('evaluations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationitemscore',
            name='rubric_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='exams.rubricitem', verbose_name='Ítem'),
        ),
    ]
