# Generated by Django 4.2.13 on 2026-03-10 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("evaluations", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("exams", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluation",
            name="evaluator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evaluations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Evaluador",
            ),
        ),
        migrations.AddField(
            model_name="evaluation",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evaluations",
                to="exams.exam",
                verbose_name="ECOE",
            ),
        ),
        migrations.AddField(
            model_name="evaluation",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evaluations",
                to="exams.station",
                verbose_name="Estación",
            ),
        ),
        migrations.AddField(
            model_name="evaluation",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evaluations",
                to="students.student",
                verbose_name="Estudiante",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="evaluationitemscore",
            unique_together={("evaluation", "rubric_item")},
        ),
        migrations.AddConstraint(
            model_name="evaluation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "FINAL")),
                fields=("exam", "station", "student"),
                name="unique_final_evaluation",
            ),
        ),
    ]
